### ISSUE TITLE
No template for CONTRIBUTING.md?

### ISSUE THREAD

**Issue by SpencerDawkins** [ietf/repo-files#13]
@larseggert - I know we've talked about this in the past week, but wanted to follow up in Github. 

I recognize the extensive customization that many working groups are doing for CONTRIBUTING.md, but I wonder if it's possible to provide a default template here, even if the default just says that anyone can contribute by opening and commenting on issues in the repository.

That would give a starting place for people who are working on individual drafts, rather than providing no CONTRIBUTING.md at all, which is probably fine for people who are looking at the repo and are experienced with Github conventions - but I created about six repos before I thought I was experienced (and I could still be wrong!), so I'm glad I was getting these templates by default. 

Do The Right Thing, of course.

**Comment by larseggert** [comment]
The template that most people start from, because they start from @martinthomson's repo, is https://github.com/martinthomson/i-d-template/blob/main/template/CONTRIBUTING.md

We already point to that in the README, do you think we need to do more?
